import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./componants/Providers";
import Script from "next/script";
import Head from "../app/componants/Head";
import Layoutwraper from "./componants/Layoutwraper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Providers should wrap everything that needs Redux */}
        <Providers>
          <Head />
          {/* Yahan Layoutwraper conditionally Navbar handle karega */}
          <Layoutwraper>{children}</Layoutwraper>
        </Providers>
      </body>
    </html>
  );
}
